# Generated by Django 4.1 on 2022-08-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationsettings",
            name="module",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="applicationsettings",
            name="setting_name",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
